---
driver:
#  name: vagrant
  name: docker
  #binary: docker.io
  use_sudo: false
  # Need: 
  #   - chef gem install --no-user-install kitchen-docker
  #   - usermod -aG docker levasju1
#driver_config:
#  provision_command: apt-get install -f upstart

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: debian-8
#  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
#    verifier:
#      inspec_tests:
#        - test/smoke/default
    attributes:
      workstation:
        packages:
          - git
        gems:
          - bundler
        scripts:
          - {
            "destination": "/usr/local/bin/goss",
            "source": "https://github.com/aelsabbahy/goss/releases/download/v0.3.5/goss-linux-amd64",
            "mode": "0755"
          }
        users:
          - {
            "name": "root",
            "home": "/root"
          }
        ssh_config:
          - name: jumpboxdev
            options:
              HostName: 54.81.79.111
              User: esljenkins
              IdentityFile: "~/.ssh/esljenkins"
            user: root
