language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4


sudo: required

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update --system
  - gem update bundler
  - gem install cookstyle

script: "bundle exec rubocop"
